spring:
  profiles:
    active: test
---
server:
  port: 9090
spring:
  profiles: test
  application:
    name: zrwl-farm-config-test
---
server:
  port: 9091
spring:
  profiles: dev
  application:
    name: zrwl-farm-config-dev

