spring:
  #配置文件
  profiles:
    active: test
server:
  port: 9090 # 应用程序监听的web端口
spring:
  #配置文件
  profiles: test
  #应用名称
  application:
    name: zrwl-farm-config-test
server:
  port: 9090 # 应用程序监听的web端口
spring:
  #配置文件
  profiles: dev
  #应用名称
  application:
    name: zrwl-farm-config-dev

